Fix building with clang 13
Clang 13 now enables cast-function-type warning which results in build
errors that look like this:

    /corefx/src/Native/Unix/System.Native/pal_process.c(382,76): error G39B05358: cast from 'void (*)(int, siginfo_t *, void *)' to 'void (*)(int)' converts to incompatible function type [-Werror,-Wcast-function-type] [/corefx/src/Native/build-native.proj]
    void (*oldhandler)(int) = (sa_old.sa_flags & SA_SIGINFO) ? (void (*)(int))sa_old.sa_sigaction : sa_old.sa_handler;
                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Disable this warning using -Wno-cast-function-type warning. That seems
lower-risk than any functional code change.

Clang 13 also enables reserved-identifier warning which results in build errors
like this:

    /corefx/src/Native/Unix/System.Native/pal_process.c(819,17): error GA61F72A6: identifier '__cpu' is reserved because it starts with '__' [-Werror,-Wreserved-identifier] [/corefx/src/Native/build-native.proj]
                      if (CPU_ISSET(cpu, &set))
                          ^
    /usr/include/sched.h:94:34: note: expanded from macro 'CPU_ISSET'
    # define CPU_ISSET(cpu, cpusetp) __CPU_ISSET_S (cpu, sizeof (cpu_set_t), \
                                     ^

This really seems like a bug in clang that it's complaining about code in
system libraries that we are using via wrapper-macros. But there are
other instances of this warning that are speciifc to our code too, such
as `__padding` in
src/Native/Unix/System.Native/pal_interfaceaddresses.h. Disable this
warning too.

Tested with Clang 13 rc1.