Fix build on NetBSD: Add missing include <sys/types.h>
In file included from /tmp/pkgsrc-tmp/wip/corefx-git/work/corefx/src/Native/System.Native/pal_interfaceaddresses.cpp:11:
/usr/include/ifaddrs.h:34:2: error: unknown type name 'u_int'
        u_int            ifa_flags;
        ^

Original solution by Peter Jas.